
def main():
    worked_list = ["Aland Is.", "Alaska", "Albania", "Algeria", "Andorra",
 "Angola", "Anguilla", "Antigua & Barbuda", "Argentina",
 "Armenia", "Aruba", "Ascension I.", "Asiatic Russia",
 "Australia", "Austria", "Azores", "Bahamas", "Balearic Is.",
 "Barbados", "Belarus", "Belgium", "Belize", "Bermuda",
 "Bolivia", "Bonaire", "Bosnia-Herzegovina", "Botswana",
 "Brazil", "British Virgin Is.", "Brunei Darussalam", "Bulgaria",
 "Burkina Faso", "Canada", "Canary Is.", "Cape Verde",
 "Cayman Is.", "Ceuta & Melilla", "Chile", "China", "Clipperton I.",
 "Colombia", "Costa Rica", "Cote d'Ivoire", "Crete", "Croatia",
 "Cuba", "Curacao", "Cyprus", "Czech Republic", "Denmark",
 "Desecheo I.", "Dominica", "Dominican Republic", "East Malaysia",
 "Eastern Kiribati", "Ecuador", "Egypt", "El Salvador", "England",
 "Estonia", "European Russia", "Falkland Is.",
 "Federal Republic of Germany", "Fernando de Noronha",
 "Finland", "France", "French Guiana", "French Polynesia",
 "Galapagos Is.", "Georgia", "Gibraltar", "Greece", "Greenland",
 "Grenada", "Guadeloupe", "Guam", "Guantanamo Bay", "Guatemala",
 "Guernsey", "Guinea", "Guyana", "Haiti", "Hawaii", "Honduras",
 "Hungary", "Iceland", "India", "Indonesia", "Ireland",
 "Isle of Man", "Israel", "Italy", "Jamaica", "Japan",
 "Jersey", "Johnston I.", "Kazakhstan", "Kenya",
 "Kingdom of eSwatini", "Kuwait", "Kyrgyzstan", "Latvia",
 "Lebanon", "Lesotho", "Liberia", "Lithuania", "Lord Howe I.",
 "Luxembourg", "Madeira Is.", "Malawi", "Mali", "Malta",
 "Mariana Is.", "Marquesas Is.", "Marshall Is.", "Martinique",
 "Mayotte", "Mexico", "Micronesia", "Moldova", "Montenegro",
 "Montserrat", "Morocco", "Mozambique", "Namibia", "Navassa I.",
 "Netherlands", "New Caledonia", "New Zealand", "Nicaragua",
 "North Cook Is.", "Northern Ireland", "Norway", "Panama",
 "Papua New Guinea", "Paraguay", "Peru", "Philippines",
 "Pitcairn I.", "Poland", "Portugal", "Puerto Rico", "Qatar",
 "Republic of Korea", "Republic of Kosovo", "Republic of the Congo",
 "Reunion I.", "Revillagigedo", "Romania", "Rwanda",
 "Saba & St. Eustatius", "Sable I.", "Samoa",
 "San Andres & Providencia", "San Marino", "Sao Tome & Principe",
 "Sardinia", "Saudi Arabia", "Scotland", "Senegal", "Serbia",
 "Sierra Leone", "Sint Maarten", "Slovak Republic", "Slovenia",
 "South Africa", "South Cook Is.", "Spain", "St. Helena",
 "St. Kitts & Nevis", "St. Lucia", "St. Paul I.", "St. Vincent",
 "Suriname", "Svalbard", "Sweden", "Switzerland", "Syria",
 "Tajikistan", "The Gambia", "Togo", "Tokelau Is.",
 "Trindade & Martim Vaz Is.", "Trinidad & Tobago", "Tunisia",
 "Turks & Caicos Is.", "Uganda", "Ukraine", "United Nations HQ",
 "Uruguay", "US Virgin Is.", "USA", "Uzbekistan", "Venezuela",
 "Wake I.", "Wales"]

    return worked_list
